https://household-backend.azurewebsites.net



// ___AUTHENTICATE___ //
###
POST https://household-backend.azurewebsites.net/api/V01/Authenticate/login
content-type: application/json

{
  "username": "tuco54",
  "password": "password_A1"
}
###
POST https://household-backend.azurewebsites.net/api/V01/Authenticate/register
content-type: application/json

{
  "username": "tuco54",
  "password": "password_A1"
}



// ___PROFILE___ //

###
// GetByProfileId
GET https://localhost:7018/api/v01/profile/GetByProfileId/B0000000-0000-0000-0000-000000000001

###
// GetByHouseholdId
GET https://localhost:7018/api/v01/profile/GetByHouseholdId/c0000000-0000-0000-0000-000000000001

###
// GetByUserId
GET https://localhost:7018/api/v01/profile/GetByAuthUserId/90000000-0000-0000-0000-000000000001

###
// CreateProfile
// Obs skapa egen token
POST https://localhost:7018/api/v01/profile/CreateProfile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9hbm9ueW1vdXMiOiI2ZmZhZTI4Ni1iNjRhLTRlNWEtYWFiZC04OTAzOTRmOWE5M2MiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidHVjbzU0IiwianRpIjoiZDcyNTVjNzYtMmM3Yy00NzEzLWI2MTMtZGYxNjFkYWM1OWZjIiwiZXhwIjoxNjY3NjU0NzA0LCJpc3MiOiJUcnVlIiwiYXVkIjoiVHJ1ZSJ9.a6uDTPZtQZlKLwKQHMQDune9wX11FkbqIijxTaD_5VM

{
  "alias": "Robotnik",
  "householdId": "C0000000-0000-0000-0000-000000000001",
  "isAdmin": false
}


// UpdateProfile
// Saker som går att uppdatera är:
# {
#   "Alias": "asd",
#   "IsAdmin": false,
#   "Avatar": "???",
#   "Color": "#bada55", Color has now been removed from the base object, and thus shan't be changed.
#   "PendingRequest" : false
# }
// Men allt är optional, JS style
###
PATCH https://localhost:7018/api/v01/profile/EditProfile/b0000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "Alias": "JanBananHemma"
}

###
// DeleteProfile
DELETE https://localhost:7018/api/v01/profile/DeleteProfile/b0000000-0000-0000-0000-000000000001



// ___PAUSE___ //

###
// Get first seeded Pause object
GET https://household-backend.azurewebsites.net/api/V01/Pause/GetPauseByHouseholdId/C0000000-0000-0000-0000-000000000002

###
POST https://localhost:7018/api/V01/Pause/AddPause
Content-Type: application/json

{
  "startDate": "2022-10-17T10:52:41.517Z",
  "endDate": "2022-10-17T10:52:41.517Z",
  "profileIdQol": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "householdId": "C0000000-0000-0000-0000-000000000001"
}

###
// Change the first seeded Pause object
PUT https://localhost:7018/api/V01/Pause/UpdatePause/A0000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "startDate": "2022-10-17T10:57:49.015Z",
  "endDate": "2022-10-17T10:57:49.015Z",
  "profileIdQol": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "householdId": "C0000000-0000-0000-0000-000000000001"
}



// ___HOUSEHOLD___ //

###
// Uses one of the seeded profiles to find its corresponding household.
GET https://localhost:7018/api/V01/Household/GetHouseholdByProfileId/b0000000-0000-0000-0000-000000000001

###
POST https://localhost:7018/api/V01/Household/AddHousehold
Content-Type: application/json

{
  "name": "HemmetPåBergetDärBorta",
  "code": "991105"
}

###
// Try this delete, and the household-get-endpoint will fail.
DELETE https://localhost:7018/api/V01/Household/DeleteHouseholdById/c0000000-0000-0000-0000-000000000001



// ___CHORE___ //

// Get Chore by Id
###
GET https://localhost:7018/api/V01/Chore/GetChoreById/D0000000-0000-0000-0000-000000000001


// Post a Chore
###
POST https://localhost:7018/api/V01/Chore/AddChore
Content-Type: application/json

{
  "name": "string",
  "points": 0,
  "description": "string",
  "pictureUrl": "string",
  "audioUrl": "string",
  "frequency": 0,
  "isArchived": true,
  "householdId": "3fa85f64-5717-4562-b3fc-2c963f66afa2"
}

// Patch the first seeded chore
###
PATCH https://localhost:7018/api/V01/Chore/UpdateChore/D0000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "name": "string",
  "points": 2,
  "description": "string",
  "pictureUrl": "string",
  "audioUrl": "string",
  "frequency": 4,
  "isArchived": false,
  "householdId": "3fa85f64-5717-4562-b3fc-2c963f66afa9"
}

// Delete the first seeded chore
###
DELETE https://localhost:7018/api/V01/Chore/DeleteChore/D0000000-0000-0000-0000-000000000001
