https://household-backend.azurewebsites.net
h_ttps://localhost:7018

###
// Authenticate : POST : login
POST https://household-backend.azurewebsites.net/api/V01/Authenticate/login
content-type: application/json

{
  "username": "tuco54",
  "password": "password_A1"
}

###
// Authenticate : POST : register
POST https://household-backend.azurewebsites.net/api/V01/Authenticate/register
content-type: application/json

{
  "username": "tuco544",
  "password": "password_A1"
}

###
// Chore : GET : GetChoreById
GET https://household-backend.azurewebsites.net/api/V01/Chore/GetChoreById/D0000000-0000-0000-0000-000000000001

###
// Chore : GET : GetChoresByHouseholdId
GET https://household-backend.azurewebsites.net/api/V01/Chore/GetChoresByHouseholdId/C0000000-0000-0000-0000-000000000003

###
// Chore : POST : AddChore
POST https://household-backend.azurewebsites.net/api/V01/Chore/AddChore
Content-Type: application/json

{
  "name": "Torka hyllorna i köket!!!",
  "points": 10,
  "description": "Ovan spis och ovan kyl+frys",
  "pictureUrl": "",
  "audioUrl": "",
  "frequency": 0,
  "isArchived": false,
  "householdId": "C0000000-0000-0000-0000-000000000003"
}

###
// Chore : PATCH : UpdateChore
PATCH https://household-backend.azurewebsites.net/api/V01/Chore/UpdateChore/d0000000-0000-0000-0000-000000000001
Content-Type: application/json

{
    "name": "Ojoj, biltvätt igen",
    "points": 8,
    "description": "Tvätta bilen utvänding ocn invändigt OCH SLÄPET!!",
    "pictureUrl": "",
    "audioUrl": "",
    "frequency": 14,
    "isArchived": false,
    "householdId": "c0000000-0000-0000-0000-000000000003"
}

###
// Chore : DELETE : DeleteChore (funkar men svarar med 204)
DELETE https://household-backend.azurewebsites.net/api/V01/Chore/DeleteChore/60A9A8ED-E8DE-48CB-6DC1-08DAB781CB5E

###
// ChoreCompleted : GET : GetAllChoreCompleted
GET https://household-backend.azurewebsites.net/api/V01/ChoreCompleted/GetAllChoreCompletedByHouseholdId/C0000000-0000-0000-0000-000000000003

###
// GetChoreCompleted : GET : GetChoreCompletedByHouseholdIdAndByRange
GET https://household-backend.azurewebsites.net/api/V01/ChoreCompleted/GetChoreCompletedByHouseholdIdAndByRange/C0000000-0000-0000-0000-000000000003?start=2018-03-20T09%3A12%3A28Z&end=2023-03-20T09%3A12%3A28Z

###
// GetChoreCompleted : GET : GetChoreCompletedByHouseholdId
GET https://household-backend.azurewebsites.net/api/V01/ChoreCompleted/GetChoreCompletedById/5d8f3259-8136-4dad-7187-08dab80895e9

###
// ChoreCompleted : POST : AddChoreCompleted
POST https://household-backend.azurewebsites.net/api/V01/ChoreCompleted/AddChoreCompleted
Content-Type: application/json

{
  "completedAt": "2022-10-27T09:43:04.405Z",
  "profileIdQol": "B0000000-0000-0000-0000-000000000001",
  "choreId": "D0000000-0000-0000-0000-000000000004",
  "householdId": "C0000000-0000-0000-0000-000000000001"
}

###
// Household : GET : GetHouseholdByProfileId
GET https://household-backend.azurewebsites.net/api/V01/Household/GetHouseholdByProfileId/B0000000-0000-0000-0000-000000000007

###
// Household : GET : GetHouseholdById
GET https://household-backend.azurewebsites.net/api/V01/Household/GetHouseholdById/c21554ca-2865-40fc-e088-08dab80e7184

###
// Household : GET : GetHouseholdByHouseholdCode
GET https://household-backend.azurewebsites.net/api/V01/Household/GetHouseholdByHouseholdCode/666

###
// Household : POST : AddHousehold
POST https://household-backend.azurewebsites.net/api/V01/Household/AddHousehold
Content-Type: application/json

{
  "name": "Anna och Tuco2"
}

###
// Household : DELETE : DeleteHouseholdById
DELETE https://household-backend.azurewebsites.net/api/V01/Household/DeleteHouseholdById/7DCF8219-3F5F-4097-8A3B-08DAB789ADFD

###
// Pause : GET : GetPauseById
GET https://household-backend.azurewebsites.net/api/V01/Pause/GetPauseById/A0000000-0000-0000-0000-000000000003


###
// Pause : GET : GetPauseByHouseholdId
GET https://household-backend.azurewebsites.net/api/V01/Pause/GetPauseByHouseholdId/C0000000-0000-0000-0000-000000000003

###
// Pause : POST : AddPause
POST https://household-backend.azurewebsites.net/api/V01/Pause/AddPause
Content-Type: application/json

{
  "startDate": "2022-10-17T10:52:44.517Z",
  "endDate": "2022-11-17T10:52:41.517Z",
  "profileIdQol": "B0000000-0000-0000-0000-000000000007",
  "householdId": "C0000000-0000-0000-0000-000000000003"
}

###
// Pause : PUT : UpdatePause
PUT https://household-backend.azurewebsites.net/api/V01/Pause/UpdatePause/966B87DE-65B2-42DF-DB09-08DABA659E4F
Content-Type: application/json

{
  "endDate": "2022-12-17T10:52:41.517Z",
  "householdId": "C0000000-0000-0000-0000-000000000003"
}

###
// Profile : GET : GetProfileById
GET https://household-backend.azurewebsites.net/api/v01/profile/GetByProfileId/B0000000-0000-0000-0000-000000000004

###
// Profile : GET : GetProfileByHouseholdId
GET https://household-backend.azurewebsites.net/api/v01/profile/GetByHouseholdId/c0000000-0000-0000-0000-000000000001

###
// Profile : POST : GetByUserId
GET https://household-backend.azurewebsites.net/api/V01/Profile/GetByUserId/286C4279-BCE5-4DBD-830A-10D2AAB95ECD

###
// Profile : POST : CreateProfile
POST https://household-backend.azurewebsites.net/api/v01/profile/CreateProfile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9hbm9ueW1vdXMiOiI2ZmZhZTI4Ni1iNjRhLTRlNWEtYWFiZC04OTAzOTRmOWE5M2MiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidHVjbzU0IiwianRpIjoiZDcyNTVjNzYtMmM3Yy00NzEzLWI2MTMtZGYxNjFkYWM1OWZjIiwiZXhwIjoxNjY3NjU0NzA0LCJpc3MiOiJUcnVlIiwiYXVkIjoiVHJ1ZSJ9.a6uDTPZtQZlKLwKQHMQDune9wX11FkbqIijxTaD_5VM

{
  "alias": "Robotnik3!",
  "householdId": "C0000000-0000-0000-0000-000000000001",
  "isAdmin": false
}

###
// Profile : PATCH : EditProfile
PATCH https://household-backend.azurewebsites.net/api/v01/profile/EditProfile/3073EC2F-EF6A-46AC-3BF0-08DAB78CF931
Content-Type: application/json

{
  "alias": "KalleString",
  "isAdmin": true,
  "avatar": "string",
  "pendingRequest": true
}

###
// Profile : DELETE : DeleteProfile
DELETE https://household-backend.azurewebsites.net/api/v01/profile/DeleteProfile/3073EC2F-EF6A-46AC-3BF0-08DAB78CF931

